export const ON_LOGIN = 'ON_LOGIN';
export const ON_LOGIN_SUCCESS = 'ON_LOGIN_SUCCESS';
export const ON_LOGIN_ERROR = 'ON_LOGIN_ERROR';
export const ON_LOGOUT = 'ON_LOGOUT';
export const ON_INVALID_AUTH = 'ON_INVALID_AUTH';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';

export const ON_UPDATE_SYSTEM_STATUS = 'ON_UPDATE_SYSTEM_STATUS';
export const ON_UPDATE_DISK_INFO = 'ON_UPDATE_DISK_INFO';
export const ON_UPDATE_DISK_IO_INFO = 'ON_UPDATE_DISK_IO_INFO';
export const ON_UPDATE_SYSTEM_INFORMATION = 'ON_UPDATE_SYSTEM_INFORMATION';
